### ISSUE TITLE
Code Optimization REQUEST

### ISSUE THREAD

**Issue by ghost** [Raznar-Lab/MobDespawner#2]
- First of all, this plugin is great, but i'd request code optimization. Seperating the events from Main class to multiple classes. Example: SomeEventInMain -> src/main/listeners/event.class

Why?

1. Better plugin performance.

- Plugin configuration, as every plugin needs configuration, this plugin specially needs it, some server owners want to optimize their mobs. (PerMob support, PerWorld support)

**Comment by MoonLythz** [comment]
This could be a great idea, especially if this plugin expand with configuration (e.g. config for mob or world exception etc) plus again, better performance and more it'll be more organized.

**Comment by NotYusta** [comment]
Great Idea, i'll add it soon with @KJosh541

**Comment by NotYusta** [comment]
> 
> 
>     * First of all, this plugin is great, but i'd request code optimization. Seperating the events from Main class to multiple classes. Example: SomeEventInMain -> src/main/listeners/event.class
> 
> 
> Why?
> 
>     1. Better plugin performance.
> 
> 
>     * Plugin configuration, as every plugin needs configuration, this plugin specially needs it, some server owners want to optimize their mobs. (PerMob support, PerWorld support)

I've done with the code optimization, the configuration will be published soon

**Comment by NotYusta** [comment]
also this plugin will supports 1.12 - 1.16.4 Minecraft Version

**Comment by NotYusta** [comment]
Done, flexible configuration has been added check it out on https://www.spigotmc.org/resources/server-stonker.86590/ , dont forget to leave a review 👍
