### ISSUE TITLE
wiki is dead..

### ISSUE THREAD

**Issue by Pesoen** [Raznar-Lab/MobDespawner#3]
the config file links to the wiki, but the wiki is empty, so there is no way to know what the config file does, other than experiment and see what happens.. please make a wiki or add commenting to the config so we know what it does..

**Comment by MoonLythz** [comment]
Hey there! 

Thanks for the feedback! Don't worry, we'll be adding a wiki soon ~~(we _kinda_ forget about it?)~~.. This **_may_** take a while as our developers is kinda busy.. So yeah, we'll get back when the wiki is done!

Regards,

**MoonLight**

**Comment by MoonLythz** [comment]
**The wiki is now done! :)**

Sorry that it took a long time to make the wiki, but nonetheless it's finally done!
Here it is: _[ServerStonker's wiki](https://github.com/Raznar-Lab/ServerStonker/wiki)_

Please let me know if I can help with anything else..
